if status is-interactive
    abbr --add gc 'git checkout'
    abbr --add _gc 'my_git_checkout_branch_peco'
    abbr --add gcb 'git checkout -b'
    abbr --add fgc 'my_git_checkout_branch'
    abbr --add fgcc 'my_git_checkout_commit'
    abbr --add gb 'git branch'
    abbr --add gba 'git fetch --prune && git branch -a'
    abbr --add _gbd 'my_git_delete_branch_peco'
    abbr --add gaa 'git add -A'
    abbr --add gcm 'git commit'
    abbr --add gca 'git commit --amend'
    abbr --add grih 'my_git_rebase_interactive_head'
    abbr --add grc 'git rebase --continue'
    abbr --add gps 'git push'
    abbr --add gpl 'git symbolic-ref --short HEAD | xargs -I {} git pull origin {}'
    abbr --add gs 'git stash -u'
    abbr --add gsp 'git stash pop'
    abbr --add _gsa 'my_git_stash_apply_peco'
    abbr --add _gsaf 'my_git_stash_checkout_peco'
    abbr --add _gsd 'my_git_stash_drop_peco'
    abbr --add gsl 'git stash list'
    abbr --add _gss 'my_git_stash_show_peco'
    abbr --add gp 'git remote prune origin'
    abbr --add guisw 'git update-index --skip-worktree'
    abbr --add guinsw 'git update-index --no-skip-worktree'
    abbr --add guils 'git ls-files -t | grep ^S'
    abbr --add grs 'git reset --soft HEAD^'
    abbr --add gcp 'git cherry-pick'
    abbr --add gl 'git log --oneline'
    abbr --add gm 'git merge'
end
